//
//  TournamentsTemplateManager.swift
//  TennisBusiness
//
//  Created by Nikolay Mikhailishin on 9/29/19.
//  Copyright © 2019 nikolay.mihailishin. All rights reserved.
//

import Foundation
import Swinject

protocol TournamentsTemplateManager: class {
    var tournamentsTemplate: [TournamentTemplate] { get }
}

final class TournamentsTemplateManagerImp: TournamentsTemplateManager, ResolverInitializable {
    // MARK: - Properties
    
    let tournamentsTemplate: [TournamentTemplate]
    private let countriesDataManager: CountriesDataManager
    
    
    
    // MARK: - ResolverInitializable
    
    convenience init?(resolver: Resolver) {
        guard let countriesDataManager = resolver.resolve(CountriesDataManager.self) else {
            print("Warning: Failed to initilize all needed dependencies!")
            return nil
        }
        self.init(countriesDataManager: countriesDataManager)
    }
    
    
    
    // MARK: - Init
    
    init(countriesDataManager: CountriesDataManager) {
        let countries = countriesDataManager.countries
        self.countriesDataManager = countriesDataManager
        self.tournamentsTemplate = [
            TournamentTemplate(name: "Qatar ExxonMobil Open",
                               city: "Doha",
                               country: countries.findCountry(withName: "Qatar"),
                               start: (month: 12, day: 31),
                               week: 1,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 1416205,
                               points: .atp250,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Brisbane International",
                               city: "Brisbane",
                               country: countries.findCountry(withName: "Australia"),
                               start: (month: 12, day: 31),
                               week: 1,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 589680,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Tata Open Maharashtra",
                               city: "Pune",
                               country: countries.findCountry(withName: "India"),
                               start: (month: 12, day: 31),
                               week: 1,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 589680,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Sydney International",
                               city: "Sydney",
                               country: countries.findCountry(withName: "Australia"),
                               start: (month: 1, day: 6),
                               week: 2,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 589680,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "ASB Classic",
                               city: "Auckland",
                               country: countries.findCountry(withName: "New Zealand"),
                               start: (month: 1, day: 7),
                               week: 2,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 589680,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Australian Open",
                               city: "Melbourne",
                               country: countries.findCountry(withName: "Australia"),
                               start: (month: 1, day: 14),
                               week: 3,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 29687000,
                               points: .grandSlam,
                               draw: (single: 128, double: 64)),
            TournamentTemplate(name: "Cordoba Open",
                               city: "Cordoba",
                               country: countries.findCountry(withName: "Argentina"),
                               start: (month: 2, day: 4),
                               week: 6,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 589680,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Open Sud de France",
                               city: "Montpellier",
                               country: countries.findCountry(withName: "France"),
                               start: (month: 2, day: 4),
                               week: 6,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Sofia Open",
                               city: "Sofia",
                               country: countries.findCountry(withName: "Bulgaria"),
                               start: (month: 2, day: 4),
                               week: 6,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "ABN AMRO World Tennis Tournament",
                               city: "Rotterdam",
                               country: countries.findCountry(withName: "Netherlands"),
                               start: (month: 2, day: 11),
                               week: 7,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 2098480,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "New York Open",
                               city: "New York",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 2, day: 11),
                               week: 7,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 777385,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Argentina Open",
                               city: "Buenos Aires",
                               country: countries.findCountry(withName: "Argentina"),
                               start: (month: 2, day: 11),
                               week: 7,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 673135,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Rio Open presented by Claro",
                               city: "Rio de Janeiro",
                               country: countries.findCountry(withName: "Brazil"),
                               start: (month: 2, day: 18),
                               week: 8,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 1937740,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Open 13 Provence",
                               city: "Marseille",
                               country: countries.findCountry(withName: "France"),
                               start: (month: 2, day: 18),
                               week: 8,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 744010,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Delray Beach Open by VITACOST.com",
                               city: "Delray Beach",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 2, day: 18),
                               week: 8,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 651215,
                               points: .atp250,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Dubai Duty Free Tennis Championships",
                               city: "Dubai",
                               country: countries.findCountry(withName: "United Arab Emirates"),
                               start: (month: 2, day: 25),
                               week: 9,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 2887895,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Abierto Mexicano Telcel presentado por HSBC",
                               city: "Acapulco",
                               country: countries.findCountry(withName: "Mexico"),
                               start: (month: 2, day: 25),
                               week: 9,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 1931110,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Brasil Open",
                               city: "Sao Paulo",
                               country: countries.findCountry(withName: "Brazil"),
                               start: (month: 2, day: 25),
                               week: 9,
                               surface: .clay,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 618810,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "BNP Paribas Open",
                               city: "Indian Wells",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 3, day: 7),
                               week: 10,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 9314875,
                               points: .atp1000,
                               draw: (single: 96, double: 32)),
            TournamentTemplate(name: "Miami Open presented by Itau",
                               city: "Miami",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 3, day: 20),
                               week: 12,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 9314875,
                               points: .atp1000,
                               draw: (single: 96, double: 32)),
            TournamentTemplate(name: "Fayez Sarofim & Co. U.S. Men's Clay Court Championship",
                               city: "Houston",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 4, day: 8),
                               week: 15,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 652245,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Grand Prix Hassan II",
                               city: "Marrakech",
                               country: countries.findCountry(withName: "Morocco"),
                               start: (month: 4, day: 8),
                               week: 15,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Rolex Monte-Carlo Masters",
                               city: "Monte Carlo",
                               country: countries.findCountry(withName: "Monaco"),
                               start: (month: 4, day: 14),
                               week: 16,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 5585030,
                               points: .atp1000,
                               draw: (single: 56, double: 32)),
            TournamentTemplate(name: "Barcelona Open Banc Sabadell",
                               city: "Barcelona",
                               country: countries.findCountry(withName: "Spain"),
                               start: (month: 4, day: 22),
                               week: 17,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 2746455,
                               points: .atp500,
                               draw: (single: 48, double: 16)),
            TournamentTemplate(name: "Hungarian Open",
                               city: "Budapest",
                               country: countries.findCountry(withName: "Hungary"),
                               start: (month: 4, day: 22),
                               week: 17,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "BMW Open by FWU",
                               city: "Munich",
                               country: countries.findCountry(withName: "Germany"),
                               start: (month: 4, day: 29),
                               week: 18,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Millennium Estoril Open",
                               city: "Estoril",
                               country: countries.findCountry(withName: "Portugal"),
                               start: (month: 4, day: 29),
                               week: 18,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Mutua Madrid Open",
                               city: "Madrid",
                               country: countries.findCountry(withName: "Spain"),
                               start: (month: 5, day: 5),
                               week: 19,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 7279270,
                               points: .atp1000,
                               draw: (single: 56, double: 32)),
            TournamentTemplate(name: "Internazionali BNL d'Italia",
                               city: "Rome",
                               country: countries.findCountry(withName: "Italy"),
                               start: (month: 5, day: 12),
                               week: 20,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 5791280,
                               points: .atp1000,
                               draw: (single: 56, double: 32)),
            TournamentTemplate(name: "Banque Eric Sturdza Geneva Open",
                               city: "Geneva",
                               country: countries.findCountry(withName: "Switzerland"),
                               start: (month: 5, day: 19),
                               week: 21,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Open Parc Auvergne-Rhone-Alpes Lyon",
                               city: "Lyon",
                               country: countries.findCountry(withName: "France"),
                               start: (month: 5, day: 19),
                               week: 21,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Roland Garros",
                               city: "Paris",
                               country: countries.findCountry(withName: "France"),
                               start: (month: 5, day: 26),
                               week: 22,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 20060000,
                               points: .grandSlam,
                               draw: (single: 128, double: 64)),
            TournamentTemplate(name: "MercedesCup",
                               city: "Stuttgart",
                               country: countries.findCountry(withName: "Germany"),
                               start: (month: 6, day: 10),
                               week: 24,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 754540,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Libema Open",
                               city: "s-Hertogenbosch",
                               country: countries.findCountry(withName: "Netherlands"),
                               start: (month: 6, day: 10),
                               week: 24,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 711275,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Fever-Tree Championships",
                               city: "London",
                               country: countries.findCountry(withName: "United Kingdom"),
                               start: (month: 6, day: 17),
                               week: 25,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 2219150,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "NOVENTI OPEN",
                               city: "Halle",
                               country: countries.findCountry(withName: "Germany"),
                               start: (month: 6, day: 17),
                               week: 25,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 2219150,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Turkish Airlines Open Antalya",
                               city: "Antalya",
                               country: countries.findCountry(withName: "Turkey"),
                               start: (month: 6, day: 23),
                               week: 26,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 507490,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Nature Valley International",
                               city: "Eastbourne",
                               country: countries.findCountry(withName: "United Kingdom"),
                               start: (month: 6, day: 24),
                               week: 26,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 745880,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Wimbledon",
                               city: "London",
                               country: countries.findCountry(withName: "United Kingdom"),
                               start: (month: 7, day: 1),
                               week: 27,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 17769000,
                               points: .grandSlam,
                               draw: (single: 128, double: 64)),
            TournamentTemplate(name: "Hall of Fame Open",
                               city: "Newport",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 7, day: 14),
                               week: 29,
                               surface: .grass,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 652245,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Plava Laguna Croatia Open Umag",
                               city: "Umag",
                               country: countries.findCountry(withName: "Croatia"),
                               start: (month: 7, day: 15),
                               week: 29,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Swedish Open",
                               city: "Bastad",
                               country: countries.findCountry(withName: "Sweden"),
                               start: (month: 7, day: 15),
                               week: 29,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Hamburg European Open",
                               city: "Hamburg",
                               country: countries.findCountry(withName: "Germany"),
                               start: (month: 7, day: 22),
                               week: 30,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 1855490,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "BB&T Atlanta Open",
                               city: "Atlanta",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 7, day: 22),
                               week: 30,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 777385,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "J. Safra Sarasin Swiss Open Gstaad",
                               city: "Gstaad",
                               country: countries.findCountry(withName: "Switzerland"),
                               start: (month: 7, day: 22),
                               week: 30,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Citi Open",
                               city: "Washington",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 7, day: 27),
                               week: 31,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 2046340,
                               points: .atp500,
                               draw: (single: 48, double: 16)),
            TournamentTemplate(name: "Abierto de Tenis Mifel presentado por Cinemex",
                               city: "Los Cabos",
                               country: countries.findCountry(withName: "Mexico"),
                               start: (month: 7, day: 29),
                               week: 31,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 858565,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Generali Open",
                               city: "Kitzbuhel",
                               country: countries.findCountry(withName: "Austria"),
                               start: (month: 7, day: 29),
                               week: 31,
                               surface: .clay,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Coupe Rogers",
                               city: "Montreal",
                               country: countries.findCountry(withName: "Canada"),
                               start: (month: 8, day: 5),
                               week: 32,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 6338885,
                               points: .atp1000,
                               draw: (single: 56, double: 32)),
            TournamentTemplate(name: "Western & Southern Open",
                               city: "Cincinnati",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 8, day: 11),
                               week: 33,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 6735690,
                               points: .atp1000,
                               draw: (single: 56, double: 32)),
            TournamentTemplate(name: "Winston-Salem Open",
                               city: "Winston-Salem",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 8, day: 18),
                               week: 34,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 807210,
                               points: .atp250,
                               draw: (single: 48, double: 16)),
            TournamentTemplate(name: "US Open",
                               city: "New York",
                               country: countries.findCountry(withName: "United States"),
                               start: (month: 8, day: 26),
                               week: 35,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 28619350,
                               points: .grandSlam,
                               draw: (single: 128, double: 64)),
            TournamentTemplate(name: "St. Petersburg Open",
                               city: "St. Petersburg",
                               country: countries.findCountry(withName: "Russian Federation"),
                               start: (month: 9, day: 15),
                               week: 38,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 1248665,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Moselle Open",
                               city: "Metz",
                               country: countries.findCountry(withName: "France"),
                               start: (month: 9, day: 15),
                               week: 38,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 586140,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Chengdu Open",
                               city: "Chengdu",
                               country: countries.findCountry(withName: "China"),
                               start: (month: 9, day: 23),
                               week: 39,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 1213295,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Huajin Securities Zhuhai Championships",
                               city: "Zhuhai",
                               country: countries.findCountry(withName: "China"),
                               start: (month: 9, day: 23),
                               week: 39,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 1000000,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "China Open",
                               city: "Beijing",
                               country: countries.findCountry(withName: "China"),
                               start: (month: 9, day: 30),
                               week: 40,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 3666275,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Rakuten Japan Open Tennis Championships",
                               city: "Tokyo",
                               country: countries.findCountry(withName: "Japan"),
                               start: (month: 9, day: 30),
                               week: 40,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 2046340,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Rolex Shanghai Masters",
                               city: "Shanghai",
                               country: countries.findCountry(withName: "China"),
                               start: (month: 10, day: 6),
                               week: 41,
                               surface: .hard,
                               surfaceType: .outdoor,
                               totalFinancialCommitment: 8322885,
                               points: .atp1000,
                               draw: (single: 56, double: 32)),
            TournamentTemplate(name: "VTB Kremlin Cup",
                               city: "Moscow",
                               country: countries.findCountry(withName: "Russian Federation"),
                               start: (month: 10, day: 14),
                               week: 42,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 922520,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "European Open",
                               city: "Antwerp",
                               country: countries.findCountry(withName: "Belgium"),
                               start: (month: 10, day: 14),
                               week: 42,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 711275,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Intrum Stockholm Open",
                               city: "Stockholm",
                               country: countries.findCountry(withName: "Sweden"),
                               start: (month: 10, day: 14),
                               week: 42,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 711275,
                               points: .atp250,
                               draw: (single: 28, double: 16)),
            TournamentTemplate(name: "Erste Bank Open",
                               city: "Vienna",
                               country: countries.findCountry(withName: "Austria"),
                               start: (month: 10, day: 21),
                               week: 43,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 2443810,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Swiss Indoors Basel",
                               city: "Basel",
                               country: countries.findCountry(withName: "Switzerland"),
                               start: (month: 10, day: 21),
                               week: 43,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 2219975,
                               points: .atp500,
                               draw: (single: 32, double: 16)),
            TournamentTemplate(name: "Rolex Paris Masters",
                               city: "Paris",
                               country: countries.findCountry(withName: "France"),
                               start: (month: 10, day: 28),
                               week: 44,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 5791280,
                               points: .atp1000,
                               draw: (single: 48, double: 32)),
            TournamentTemplate(name: "Next Gen ATP Finals",
                               city: "Milan",
                               country: countries.findCountry(withName: "Italy"),
                               start: (month: 11, day: 5),
                               week: 45,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 1397400,
                               points: .nextGen,
                               draw: (single: 8, double: 0)),
            TournamentTemplate(name: "Nitto ATP Finals",
                               city: "London",
                               country: countries.findCountry(withName: "United Kingdom"),
                               start: (month: 11, day: 10),
                               week: 46,
                               surface: .hard,
                               surfaceType: .indoor,
                               totalFinancialCommitment: 9000000,
                               points: .atpFinals,
                               draw: (single: 8, double: 8))
        ]
    }
}
